import { StyleSheet, Dimensions } from 'react-native'

const { width, height } = Dimensions.get('window')

export const colors = {
  // Luxurious color palette
  primary: '#1a1a2e', // Deep Navy
  primaryLight: '#2d3561',
  primaryDark: '#0f0f1e',
  secondary: '#d4af37', // Gold
  secondaryLight: '#e8c547',
  secondaryDark: '#b8941f',
  accent: '#16213e', // Dark Blue
  accentLight: '#4a5568',
  background: '#f8f9fa',
  backgroundAlt: '#ffffff',
  card: '#ffffff',
  cardElevated: '#ffffff',
  text: '#1a1a2e',
  textSecondary: '#64748b',
  textLight: '#94a3b8',
  textMuted: '#cbd5e1',
  border: '#e2e8f0',
  borderLight: '#f1f5f9',
  success: '#059669',
  successLight: '#d1fae5',
  successDark: '#047857',
  warning: '#f59e0b',
  warningLight: '#fef3c7',
  warningDark: '#d97706',
  danger: '#dc2626',
  dangerLight: '#fee2e2',
  dangerDark: '#b91c1c',
  info: '#3b82f6',
  infoLight: '#dbeafe',
  gold: '#d4af37',
  goldLight: '#f4e5c2',
  silver: '#c0c0c0',
  bronze: '#cd7f32',
}

export const shadows = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 5,
  },
  xl: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  gold: {
    shadowColor: '#d4af37',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
}

export const typography = {
  h1: {
    fontSize: 32,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -0.5,
  },
  h2: {
    fontSize: 26,
    fontWeight: '600' as const,
    color: colors.text,
    letterSpacing: -0.3,
  },
  h3: {
    fontSize: 22,
    fontWeight: '600' as const,
    color: colors.text,
  },
  h4: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: colors.text,
  },
  body: {
    fontSize: 16,
    color: colors.text,
    lineHeight: 24,
  },
  bodyLarge: {
    fontSize: 18,
    color: colors.text,
    lineHeight: 28,
  },
  caption: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  small: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  label: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
}

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenContainer: {
    flex: 1,
    padding: 20,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 20,
    ...shadows.md,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cardLuxury: {
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 24,
    ...shadows.lg,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: colors.gold,
  },
  cardGold: {
    backgroundColor: 'linear-gradient(135deg, #f4e5c2 0%, #ffffff 100%)',
    borderRadius: 16,
    padding: 20,
    ...shadows.gold,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: colors.gold,
  },
  metricCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: 6,
    ...shadows.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  metricCardGold: {
    backgroundColor: colors.goldLight,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: 6,
    ...shadows.gold,
    borderWidth: 2,
    borderColor: colors.gold,
  },
  input: {
    backgroundColor: colors.card,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    marginBottom: 16,
    color: colors.text,
  },
  inputFocused: {
    borderColor: colors.gold,
    ...shadows.sm,
  },
  button: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.md,
  },
  buttonGold: {
    backgroundColor: colors.gold,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.gold,
  },
  buttonOutline: {
    backgroundColor: 'transparent',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  buttonTextOutline: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  badgeLow: {
    backgroundColor: colors.dangerLight,
    borderColor: colors.danger,
    borderWidth: 1,
  },
  badgeMedium: {
    backgroundColor: colors.warningLight,
    borderColor: colors.warning,
    borderWidth: 1,
  },
  badgeHigh: {
    backgroundColor: colors.successLight,
    borderColor: colors.success,
    borderWidth: 1,
  },
  badgeTextLow: {
    color: colors.dangerDark,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  badgeTextMedium: {
    color: colors.warningDark,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  badgeTextHigh: {
    color: colors.successDark,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 16,
  },
  dividerGold: {
    height: 2,
    backgroundColor: colors.gold,
    marginVertical: 20,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    ...typography.h3,
    marginBottom: 16,
    color: colors.primary,
  },
  tableHeader: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  tableHeaderText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.8,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  tableRowEven: {
    backgroundColor: colors.backgroundAlt,
  },
  tableCellText: {
    fontSize: 14,
    color: colors.text,
  },
})